import { defineConfig } from "eslint/config"
import tseslint from "typescript-eslint"
import reactHooks from "eslint-plugin-react-hooks"

export default defineConfig(
  {
    ignores: [
      "dist/",
      "dist-visualize/",
      "dist-next/",
      "tests/browser/harness/dist/",
      "test-results/",
      "playwright-report/",
      "node_modules/",
      ".wrangler/",
      "supabase/functions/",
      // Built by `bun run build:chat-card`.
      "public/chat-card/",
      // Generated by the TanStack Router plugin at dev/build time.
      "src/routeTree.gen.ts",
    ],
  },
  tseslint.configs.recommended,
  // Rules of React, including the React Compiler diagnostics.
  reactHooks.configs.flat.recommended,
)
