// Builds the chat card's rendered note editor (src/chat-card/cardEditor.ts)
// into one script and writes it where the MCP server inlines it into the
// show_file view. The Edge Functions deploy from the repository without
// building the app, so the built script is committed. Run it after changing
// the card editor or the app modules it uses:
//
//   bun run build:chat-card
import { writeFileSync } from "node:fs"
import path from "node:path"
import { build } from "vite"

const REPO = path.resolve(import.meta.dirname, "..")
const ENTRY = path.join(REPO, "src/chat-card/cardEditor.ts")
const OUT = path.join(REPO, "supabase/functions/mcp-server/tools/cardEditorScript.ts")

type Output = { output: Array<{ type: "chunk"; code: string } | { type: "asset" }> }

const result = (await build({
  configFile: false,
  root: REPO,
  mode: "production",
  logLevel: "warn",
  define: { "process.env.NODE_ENV": JSON.stringify("production") },
  resolve: { alias: { "@": path.join(REPO, "src") } },
  build: {
    write: false,
    minify: true,
    lib: { entry: ENTRY, formats: ["iife"], name: "elaboratingCardEditorBundle", fileName: () => "card-editor.js" },
  },
})) as Output | Output[]
const chunk = (Array.isArray(result) ? result : [result]).flatMap((entry) => entry.output).find((item) => item.type === "chunk")
if (!chunk || chunk.type !== "chunk") throw new Error("The chat card editor build produced no script.")

// The script goes inside a <script> element, where these would end it early.
const code = chunk.code.replace(/<\/(script)/gi, "<\\/$1").replace(/<!--/g, "<\\!--")
if (/<\/script|<!--/i.test(code)) throw new Error("The chat card editor script cannot be inlined.")

writeFileSync(
  OUT,
  "// Generated by `bun run build:chat-card` from src/chat-card/cardEditor.ts. Do not edit.\n" +
    "// Third-party licenses: https://elaborat.ing/third-party-notices.txt\n" +
    `export const CARD_EDITOR_SCRIPT = ${JSON.stringify(code)}\n`,
)
console.log(`Wrote ${path.relative(REPO, OUT)}: ${code.length} characters`)
