import { palettes, type PaletteColors } from './palettes';
import { DEFAULT_THEME, getAppearanceTokens, tokenProperty, type Appearance, type ColorScheme } from './tokens';

/** The token keys that are colours: every palette key, then the derived focus and unsaved-dot ring. */
export const COLOR_TOKEN_KEYS = [...(Object.keys(palettes[0].light) as Array<keyof PaletteColors>), 'focus', 'dirtyRing'] as const;

const colorKeys = (appearance: Appearance) => {
  const tokens = getAppearanceTokens(appearance);
  return COLOR_TOKEN_KEYS.map((key) => [tokenProperty(key), tokens[key]] as const);
};

const declarations = (appearance: Appearance, indent: string) =>
  [...colorKeys(appearance).map(([property, value]) => `${property}: ${value};`), `color-scheme: ${appearance.scheme};`]
    .map((line) => indent + line)
    .join('\n');

const block = (selector: string, appearance: Appearance, indent = '') =>
  `${indent}${selector} {\n${declarations(appearance, `${indent}  `)}\n${indent}}`;

/**
 * The palettes as CSS: one block per palette and scheme, selected by the
 * data-theme and data-scheme attributes AppearanceProvider sets on <html>.
 * Before the app sets them, the first paint is the default palette following
 * the device. src/features/appearance/palettes.css holds this output; run
 * `bun run palette-css` after changing palettes.ts or tokens.ts.
 */
export function buildPaletteCss(): string {
  const schemes: ColorScheme[] = ['light', 'dark'];
  return [
    '/* Generated by `bun run palette-css` from palettes.ts and tokens.ts. Do not edit. */',
    '',
    '/* First paint, before the app sets data-scheme: the default palette, dark unless the device is light. */',
    block(':root', { theme: DEFAULT_THEME, scheme: 'dark' }),
    '@media (prefers-color-scheme: light) {',
    block(':root:not([data-scheme])', { theme: DEFAULT_THEME, scheme: 'light' }, '  '),
    '}',
    ...palettes.flatMap(({ id }) =>
      schemes.map((scheme) => block(`:root[data-theme="${id}"][data-scheme="${scheme}"]`, { theme: id, scheme })),
    ),
    '',
  ].join('\n');
}
