/*!
 * Adapted from shadcn/ui (https://github.com/shadcn-ui/ui).
 *
 * MIT License
 * Copyright (c) 2023 shadcn
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
// shadcn Base UI button, generated by the official CLI (shadcn@4.21.0
// `add`, base-nova) and adapted to this repo: `cn` resolves through the
// repo alias @/lib/utils (the registry "cn" specifier does not exist here).
// Upstream: https://ui.shadcn.com/docs/components/base/button
import { Button as ButtonPrimitive } from "@base-ui/react/button"
import { cva, type VariantProps } from "class-variance-authority"
import { cn } from "@/lib/utils"

// Restyled to the style guide: 32 high (30 small), radius 9, 600 13px; the
// focus colour as a 2px outline at offset 2; disabled at 45%; pressed fills
// mixed with 12% black, and transparent ones take the raised fill.
const buttonVariants = cva(
  "group/button inline-flex shrink-0 cursor-pointer items-center justify-center gap-2 rounded-[9px] border border-transparent bg-clip-padding text-[13px] font-semibold whitespace-nowrap transition-colors outline-none select-none focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-solid focus-visible:outline-ring disabled:pointer-events-none disabled:opacity-45 aria-invalid:border-danger [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
  {
    variants: {
      variant: {
        // Primary.
        default:
          "bg-primary text-primary-foreground hover:bg-[color-mix(in_oklab,var(--accent)_94%,black)] active:bg-[color-mix(in_oklab,var(--accent)_88%,black)]",
        outline:
          "border-border bg-transparent text-muted-foreground hover:bg-[color-mix(in_oklab,var(--raised)_50%,transparent)] hover:text-foreground active:bg-(--raised) aria-expanded:bg-(--raised) aria-expanded:text-foreground",
        secondary:
          "bg-(--raised) text-foreground hover:bg-[color-mix(in_oklab,var(--raised)_94%,black)] active:bg-[color-mix(in_oklab,var(--raised)_88%,black)] aria-expanded:bg-[color-mix(in_oklab,var(--raised)_88%,black)]",
        ghost:
          "bg-transparent text-muted-foreground hover:bg-[color-mix(in_oklab,var(--raised)_50%,transparent)] hover:text-foreground active:bg-(--raised) aria-expanded:bg-(--raised) aria-expanded:text-foreground",
        // Danger outline.
        destructive:
          "border-border bg-transparent text-danger hover:bg-[color-mix(in_oklab,var(--raised)_50%,transparent)] active:bg-(--raised)",
        link: "text-(--link) underline-offset-4 hover:underline",
      },
      size: {
        default:
          "h-8 px-3.5 has-data-[icon=inline-end]:pr-3 has-data-[icon=inline-start]:pl-3",
        xs: "h-6 gap-1 rounded-[7px] px-2 text-xs has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 [&_svg:not([class*='size-'])]:size-3",
        sm: "h-[30px] gap-1.5 px-3 has-data-[icon=inline-end]:pr-2.5 has-data-[icon=inline-start]:pl-2.5",
        lg: "h-9 px-4 has-data-[icon=inline-end]:pr-3.5 has-data-[icon=inline-start]:pl-3.5",
        icon: "size-[30px] rounded-[8px]",
        "icon-xs":
          "size-6 rounded-[7px] [&_svg:not([class*='size-'])]:size-3",
        "icon-sm": "size-7 rounded-[8px]",
        "icon-lg": "size-9",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

function Button({
  className,
  variant = "default",
  size = "default",
  ...props
}: ButtonPrimitive.Props & VariantProps<typeof buttonVariants>) {
  return (
    <ButtonPrimitive
      data-slot="button"
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  )
}

export { Button, buttonVariants }
