/*!
 * Adapted from shadcn/ui (https://github.com/shadcn-ui/ui).
 *
 * MIT License
 * Copyright (c) 2023 shadcn
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
// shadcn Base UI button, generated by the official CLI (shadcn@4.21.0
// `add`, base-nova) and adapted to this repo: `cn` resolves through the
// repo alias @/lib/utils (the registry "cn" specifier does not exist here).
// Upstream: https://ui.shadcn.com/docs/components/base/button
import { Button as ButtonPrimitive } from "@base-ui/react/button"
import { cva, type VariantProps } from "class-variance-authority"
import { cn } from "@/lib/utils"

// Restyled to the style guide: 32 high (30 small, the toolbar's Save),
// radius 9, 600 13px, padding 14; the focus colour as a 2px outline at
// offset 2; disabled at 45%. Filled buttons have no border, as the style
// guide draws them; outline and destructive have the 1px panel border.
// Hover and press mix the fill 6% and 12% towards the text colour (darker
// in light mode, lighter in dark), and transparent ones take the seg fill.
// Variants: default is the primary (accent) button, secondary the seg fill,
// outline the Cancel look (muted text), ghost no border, destructive the
// danger-text outline (Delete), link a text link, and inline a text action
// inside a sentence (a banner's Compare: its colour and size, 600, underlined
// on hover; use it with size inline, whose touch target reaches 40 high
// without moving the text). Icon buttons: icon 30 (radius 8),
// icon-lg 40. touch is the phones' text button: 40 high, radius 10, 15px.
// On touch screens (pointer: coarse) every size but the extra-small ones
// grows to 40 high, so touch targets reach 40px.
const buttonVariants = cva(
  "group/button inline-flex shrink-0 cursor-pointer items-center justify-center gap-2 rounded-button bg-clip-padding text-[13px] font-semibold whitespace-nowrap transition-colors outline-none select-none focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-solid focus-visible:outline-ring disabled:pointer-events-none disabled:opacity-45 aria-invalid:border-danger motion-reduce:transition-none [&_svg]:pointer-events-none [&_svg]:shrink-0 [&_svg:not([class*='size-'])]:size-4",
  {
    variants: {
      variant: {
        default:
          "bg-primary text-primary-foreground hover:bg-[color-mix(in_oklab,var(--accent)_94%,var(--text))] active:bg-[color-mix(in_oklab,var(--accent)_88%,var(--text))]",
        outline:
          "border border-border bg-transparent text-muted-foreground hover:bg-[color-mix(in_oklab,var(--seg)_50%,transparent)] hover:text-foreground active:bg-seg aria-expanded:bg-seg aria-expanded:text-foreground",
        secondary:
          "bg-secondary text-secondary-foreground hover:bg-[color-mix(in_oklab,var(--seg)_94%,var(--text))] active:bg-[color-mix(in_oklab,var(--seg)_88%,var(--text))] aria-expanded:bg-[color-mix(in_oklab,var(--seg)_88%,var(--text))]",
        ghost:
          "bg-transparent text-muted-foreground hover:bg-[color-mix(in_oklab,var(--seg)_50%,transparent)] hover:text-foreground active:bg-seg aria-expanded:bg-seg aria-expanded:text-foreground",
        destructive:
          "border border-border bg-transparent text-destructive hover:bg-[color-mix(in_oklab,var(--seg)_50%,transparent)] active:bg-seg",
        link: "text-accent-soft-text underline-offset-4 hover:underline",
        inline: "text-current decoration-1 underline-offset-2 hover:underline",
      },
      size: {
        default:
          "h-8 px-3.5 pointer-coarse:h-10 has-data-[icon=inline-end]:pr-3 has-data-[icon=inline-start]:pl-3",
        xs: "h-6 gap-1 rounded-row px-2 text-xs has-data-[icon=inline-end]:pr-1.5 has-data-[icon=inline-start]:pl-1.5 [&_svg:not([class*='size-'])]:size-3",
        sm: "h-[30px] gap-1.5 px-3 pointer-coarse:h-10 has-data-[icon=inline-end]:pr-2.5 has-data-[icon=inline-start]:pl-2.5",
        lg: "h-9 px-4 pointer-coarse:h-10 has-data-[icon=inline-end]:pr-3.5 has-data-[icon=inline-start]:pl-3.5",
        touch: "h-10 rounded-tile px-4 text-[15px]",
        inline: "relative inline h-auto p-0 align-baseline text-[length:inherit] pointer-coarse:after:absolute pointer-coarse:after:-inset-x-2 pointer-coarse:after:-inset-y-[11px]",
        icon: "size-[30px] rounded-tool pointer-coarse:size-10",
        "icon-xs":
          "size-6 rounded-row [&_svg:not([class*='size-'])]:size-3",
        "icon-sm": "size-7 rounded-tool pointer-coarse:size-10",
        "icon-lg": "size-10 [&_svg:not([class*='size-'])]:size-5",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

function Button({
  className,
  variant = "default",
  size = "default",
  ...props
}: ButtonPrimitive.Props & VariantProps<typeof buttonVariants>) {
  return (
    <ButtonPrimitive
      data-slot="button"
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  )
}

export { Button, buttonVariants }
